apiVersion: batch/v1
kind: Job
metadata:
  name: playlist-rules-generator-job
  namespace: carlosleao
  labels:
    app: playlist-rules-generator-job
spec:
  template:
    metadata:
      labels:
        app: playlist-rules-generator-job
    spec:
      containers:
        - name: playlist-rules-generator
          image: chbmleao/playlist-rules-generator:0.1
          command: []
          volumeMounts:
            - mountPath: /app/data 
              name: shared-storage
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
      restartPolicy: Never
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: project2-pvc-carlosleao
  backoffLimit: 4
