apiVersion: batch/v1
kind: Job
metadata:
  name: playlist-rules-generator-job-2ae7808
  namespace: carlosleao
  labels:
    app: playlist-rules-generator-job
spec:
  template:
    metadata:
      labels:
        app: playlist-rules-generator-job
    spec:
      containers:
        - name: playlist-rules-generator
          image: chbmleao/playlist-rules-generator:0.7
          command: ["sh", "entrypoint.sh"]
          volumeMounts:
            - mountPath: /app/data
              name: shared-storage
      - name: redeploy-trigger
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          kubectl delete service playlist-recommender-service
          kubectl delete deploy playlist-recommender  
      restartPolicy: Never
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: project2-pvc-carlosleao
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  backoffLimit: 4
