apiVersion: batch/v1
kind: Job
metadata:
  name: playlist-rules-generator-job-e49826b215
  namespace: carlosleao
  labels:
    app: playlist-rules-generator-job
spec:
  template:
    metadata:
      labels:
        app: playlist-rules-generator-job
    spec:
      containers:
        - name: playlist-rules-generator
          image: chbmleao/playlist-rules-generator:0.10
          command: ["sh", "entrypoint.sh"]
          volumeMounts:
            - mountPath: /app/data
              name: shared-storage
      restartPolicy: Never
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: project2-pvc-carlosleao
  backoffLimit: 4
