name: Update Kubernetes Deployment YAML on CSV Change

on:
  push:
    paths:
      - "manifests/generator-job.yaml"
      - "manifests/service.yaml"
  workflow_run:
    workflows: ["Update Kubernetes Generator Job YAML on CSV Change"]
    types:
      - completed

jobs:
  update-yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Sleep for Timer
        run: sleep 300 # 5 minutes

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get commit short hash
        id: get_hash
        run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"

      - name: Modify Kubernetes deployment YAML file
        run: |
          YAML_FILE="manifests/deployment.yaml"
          HASH="${{ steps.get_hash.outputs.hash }}"

          sed -i "s/^  name: playlist-recommender.*/  name: playlist-recommender-${HASH}/" "$YAML_FILE"

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add manifests/deployment.yaml
          git commit -m "Updated Kubernetes deployment YAML with hash ${{ steps.get_hash.outputs.hash }}"
          git push
