name: Update Kubernetes YAML on CSV Change

on:
  push:
    paths:
      - "data/spotify.csv"

jobs:
  update-yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install yq
        run: |
          sudo apt-get update && sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:rmescandon/yq
          sudo apt-get update && sudo apt-get install -y yq

      - name: Get commit short hash
        id: get_hash
        run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"

      - name: Modify Kubernetes YAML file
        run: |
          YAML_FILE="manifests/generator-job.yaml" # Replace with the path to your YAML file
          HASH="${{ steps.get_hash.outputs.hash }}"

          yq eval ".metadata.name += \"-${HASH}\"" -i "$YAML_FILE"

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add manifests/generator-job.yaml
          git commit -m "Updated Kubernetes YAML with hash ${{ steps.get_hash.outputs.hash }}"
          git push
